app:
  name: kitchen-api

jwt:
  header: Authorization
  expires_in: 300
  mobile_expires_in: 600
  secret: mysecret
  
  
springfox:
  documentation:
    swagger:
      v2:
        path: /v2/api-docs
server:
  contexPath: /
  port: 8080

spring:
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization: 
      WRITE_DATES_AS_TIMESTAMPS: false
  profiles:
    active: dev
rs:
  pscode:
    firebase:
      enabled: true