/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.darkchitect.derp.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.darkchitect.derp.model.Error;
import com.darkchitect.derp.model.Ingredient;
import com.darkchitect.derp.model.Ingredients;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-07T11:49:28.117Z")

@Api(value = "ingredients", description = "the ingredients API")
public interface IngredientsApi {

    @ApiOperation(value = "Gets list of all ingredients", notes = "Returns a list containing all of the recipes", response = Ingredients.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A list of ingredients", response = Ingredients.class),
        @ApiResponse(code = 500, message = "An unexpected error occured.", response = Error.class) })
    
    @RequestMapping(value = "/api/ingredients",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Ingredients> ingredientsGet( @Min(0) @Max(100)@ApiParam(value = "Number of recipes returned", defaultValue = "20") @RequestParam(value = "pageSize", required = false, defaultValue="20") Integer pageSize,@ApiParam(value = "Page number", defaultValue = "1") @RequestParam(value = "pageNumber", required = false, defaultValue="1") Integer pageNumber);


    @ApiOperation(value = "Gets one ingredient", notes = "Returns one ingredient, corresponding with given id", response = Ingredient.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Requested ingredient by id", response = Ingredient.class),
        @ApiResponse(code = 400, message = "The queried Ingredient does not exists.", response = Void.class),
        @ApiResponse(code = 500, message = "An unexpected error occured.", response = Error.class) })
    
    @RequestMapping(value = "/api/ingredients/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Ingredient> ingredientsIdGet(@ApiParam(value = "The ID of a ingredient",required=true ) @PathVariable("id") String id);


    @ApiOperation(value = "Creates a ingredient", notes = "Adds new ingredient to the ingredients repository", response = Void.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ingredient created succesfully.", response = Void.class),
        @ApiResponse(code = 400, message = "Ingredient could not have been created!", response = Void.class),
        @ApiResponse(code = 500, message = "An unexpected error occured.", response = Error.class) })
    
    @RequestMapping(value = "/api/ingredients",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> ingredientsPost(@ApiParam(value = "The ingredient to create."  )  @Valid @RequestBody Ingredient ingredient);


    @ApiOperation(value = "Updates a ingredient", notes = "Update a ingredient in the ingredient repository", response = Void.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ingredient updated succesfully.", response = Void.class),
        @ApiResponse(code = 400, message = "Ingredient could not have been updated!", response = Void.class),
        @ApiResponse(code = 500, message = "An unexpected error occured.", response = Error.class) })
    
    @RequestMapping(value = "/api/ingredients",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> ingredientsPut(@ApiParam(value = "The ingredient to update."  )  @Valid @RequestBody Ingredient ingredient);

}
